### ISSUE TITLE
Reflected XSS

### ISSUE THREAD

**Issue by geekwright** [XoopsModules25x/xfguestbook#16]
Reported in XOOPS/XoopsCore25#674

Input 'message' in contact.php is not escaped (or sanitized) before displayed in preview:
https://github.com/XoopsModules25x/xfguestbook/blob/290aa066dfad37fb064481a1f8e7e9941a3218f4/contact.php#L113

Notes:
- Protector catches
- In Chrome, XSS Auditor refuses to execute it
- appears that contact.php link is only displayed when showemail config is enabled

**Comment by spierrard** [comment]
The flaw was found on my site (http;//www.gratilog.net) . Can you correct it?
It must exist in all sites using this xfguestbook module. 
What is the risk if it is not corrected? because it will be revealed? see
https://www.openbugbounty.org/reports/896769/
Thanks

**Comment by mambax7** [comment]
Yes, I'll be looking at it ASAP

**Comment by mambax7** [comment]
spierrard, make sure that you have the Protector activated. I'm looking at the issues right now, but my first test showed that Protector has catched the attack: "XSS found by Protector."
So as long as you use Protector, you're fine. 

But I'll post soon a general fix to it.

**Comment by spierrard** [comment]
Yes i use protector. But the guy who found this issue said : " Via Get request it has proper xss protection. but via post request its vulnerable to xss."

**Comment by mambax7** [comment]
I hope, this update fixes that: https://github.com/XoopsModules25x/xfguestbook/releases/tag/3.21_Beta-2
@dipuhasan, could you take a look? Thank you!

**Comment by dipuhasan** [comment]
Yes fixed.

**Comment by dipuhasan** [comment]
http://www.gratilog.net domain looks fixed. And they give $10 bounty today
for this work.
But any reward from xoops?

**Comment by dipuhasan** [comment]
Sorry http://www.gratilog.net/ didn't update the new version yet.

**Comment by spierrard** [comment]
My version of xfguestbook is 2.5. When i update to 3.20 or 3.21 beta 2, i have only a white page and i can't access my site any more. I have xoops 2.5.6.

**Comment by mambax7** [comment]
You'll need to update to XOOPS 2.5.10, which is much safer/secure.
What PHP version do you have? 
I see that you have bunch of older modules - do you use all of them? You might need to update them as well, since they also could have potential security issues. 
I'll be happy to advise which modules you could use to replace the old ones that you would like to keep.

**Comment by spierrard** [comment]
I want to update my version of xoops for a while because I have a lot of problems to solve (see my help request here http://www.frxoops.org/modules/newbb/viewtopic.php?topic_id=37913&forum=70 )
My current php version is: 5.3.3.3 so I am still in version 2.5.6 because I can't evolve.
I tried on a test server in version 2.5.9 (the last one translated into French) and my modules do not work because they are too old: mylink and mydownload in particular.
In addition I have a lot of content to recover (the forum and the database and all in iso and not in utf-8 so conversion problems).
Even xfgestbook version 3.21 beta 2 does not work with xoops version 2.5.9.
In short, I'm a little overwhelmed by the events.....And I lack the technical skills to do it.

**Comment by mambax7** [comment]
OK, I'll take a look if I can fix the version xfGuestbook 2.5, so you can use it for a little bit longer. 
But we'll need to move you to recent version of PHP and XOOPS, because you're opening yourself to security issues in those old versions.
Please register on www.xoops.org, and send me a PM to https://xoops.org/modules/profile/userinfo.php?uid=19563
so we can continue this conversation, and figure out how could we help you.
